@extends('layouts.app')
@section('title', 'Créer un compte professionnel - AchatHub')
@section('content')
<section class="py-4 py-lg-5 bg-light">
<div class="container" style="max-width:980px">
    <div class="row g-4 align-items-start">
        <div class="col-lg-4"><span class="badge text-bg-dark mb-3">AchatHub Pro</span><h1 class="h2 fw-bold">Créer votre compte professionnel</h1><p class="text-secondary">Ce formulaire est réservé aux entreprises, sociétés, associations et micro-entrepreneurs immatriculés en France.</p><div class="border bg-white p-3 mt-4"><strong class="d-block mb-2">Après l’inscription</strong><ol class="small text-secondary ps-3 mb-0"><li class="mb-2">Contrôle du SIRET et de l’entreprise.</li><li class="mb-2">Validation par notre équipe.</li><li>Ouverture du catalogue et des tarifs professionnels.</li></ol></div></div>
        <div class="col-lg-8"><form method="post" action="{{ route('professional.register.store') }}" class="bg-white border p-3 p-md-4">@csrf
            <h2 class="h5 fw-bold mb-3">Identité de l’entreprise</h2><div class="row g-3 mb-4">
                <div class="col-md-6"><label class="form-label" for="company_type">Type d’entreprise</label><select id="company_type" class="form-select" name="company_type" required><option value="">Sélectionner</option>@foreach(['Micro-entreprise','Entreprise individuelle','Société','Association'] as $type)<option @selected(old('company_type')===$type)>{{ $type }}</option>@endforeach</select></div>
                <div class="col-md-6"><label class="form-label" for="legal_form">Forme juridique</label><select id="legal_form" class="form-select" name="legal_form" required><option value="">Sélectionner</option>@foreach(['Micro-entrepreneur','EI','EURL','SARL','SASU','SAS','SA','SCI','Association','Autre'] as $form)<option @selected(old('legal_form')===$form)>{{ $form }}</option>@endforeach</select></div>
                <div class="col-md-7"><label class="form-label" for="business_name">Raison sociale ou nom légal</label><input id="business_name" class="form-control" name="business_name" value="{{ old('business_name') }}" required></div>
                <div class="col-md-5"><label class="form-label" for="commercial_name">Nom commercial <span class="text-secondary">(facultatif)</span></label><input id="commercial_name" class="form-control" name="commercial_name" value="{{ old('commercial_name') }}"></div>
                <div class="col-md-6"><label class="form-label" for="siren">SIREN</label><input id="siren" class="form-control" name="siren" value="{{ old('siren') }}" inputmode="numeric" maxlength="9" placeholder="9 chiffres" required></div>
                <div class="col-md-6"><label class="form-label" for="siret">SIRET de l’établissement</label><input id="siret" class="form-control" name="siret" value="{{ old('siret') }}" inputmode="numeric" maxlength="14" placeholder="14 chiffres" required></div>
                <div class="col-md-6"><label class="form-label" for="vat_number">TVA intracommunautaire <span class="text-secondary">(si applicable)</span></label><input id="vat_number" class="form-control" name="vat_number" value="{{ old('vat_number') }}" placeholder="FRXX123456789"></div>
                <div class="col-md-6"><label class="form-label" for="activity">Activité principale</label><input id="activity" class="form-control" name="activity" value="{{ old('activity') }}" placeholder="Téléphonie, supérette, coiffure..." required></div>
            </div>
            <h2 class="h5 fw-bold mb-3">Responsable et siège</h2><div class="row g-3 mb-4">
                <div class="col-md-6"><label class="form-label" for="manager_first_name">Prénom du responsable</label><input id="manager_first_name" class="form-control" name="manager_first_name" value="{{ old('manager_first_name') }}" required></div><div class="col-md-6"><label class="form-label" for="manager_last_name">Nom du responsable</label><input id="manager_last_name" class="form-control" name="manager_last_name" value="{{ old('manager_last_name') }}" required></div>
                <div class="col-md-6"><label class="form-label" for="email">E-mail professionnel</label><input id="email" class="form-control" type="email" name="email" value="{{ old('email') }}" required></div><div class="col-md-6"><label class="form-label" for="phone">Téléphone professionnel</label><input id="phone" class="form-control" name="phone" value="{{ old('phone') }}" required></div>
                <div class="col-12"><label class="form-label" for="address">Adresse du siège ou de l’établissement</label><input id="address" class="form-control" name="address" value="{{ old('address') }}" required></div><div class="col-md-4"><label class="form-label" for="postal_code">Code postal</label><input id="postal_code" class="form-control" name="postal_code" value="{{ old('postal_code') }}" inputmode="numeric" maxlength="5" required></div><div class="col-md-8"><label class="form-label" for="city">Ville</label><input id="city" class="form-control" name="city" value="{{ old('city') }}" required></div>
            </div>
            <h2 class="h5 fw-bold mb-3">Sécurité du compte</h2><div class="row g-3"><div class="col-md-6"><label class="form-label" for="password">Mot de passe</label><input id="password" class="form-control" type="password" name="password" minlength="12" required><div class="form-text">12 caractères minimum avec lettres et chiffres.</div></div><div class="col-md-6"><label class="form-label" for="password_confirmation">Confirmer le mot de passe</label><input id="password_confirmation" class="form-control" type="password" name="password_confirmation" required></div><div class="col-12"><div class="form-check"><input id="terms" class="form-check-input" type="checkbox" name="terms" value="1" required><label class="form-check-label" for="terms">Je certifie être autorisé à représenter cette entreprise, j’accepte les <a href="{{ route('legal.terms') }}" target="_blank">conditions générales</a> et reconnais avoir lu la <a href="{{ route('legal.privacy') }}" target="_blank">politique de confidentialité</a>.</label></div></div><div class="col-12"><button class="btn btn-warning btn-lg w-100">Créer mon compte professionnel</button></div></div>
        </form><p class="text-center mt-3 mb-0">Déjà inscrit ? <a href="{{ route('professional.login') }}">Connexion professionnelle</a></p></div>
    </div>
</div>
</section>
@endsection
