@extends('layouts.admin')
@section('title','Profil de '.$customer->name)
@section('admin-content')
<div class="d-flex flex-wrap justify-content-between gap-3 mb-4"><div><a href="{{ route('admin.customers') }}" class="small text-decoration-none">← Liste des clients</a><h1 class="h3 mb-0">{{ $customer->name }}</h1><span>Profil client n°{{ $customer->id }}</span></div>@if($customer->conversation)<a class="btn btn-dark" href="{{ route('admin.conversations.show',$customer->conversation) }}"><i class="bi bi-chat-dots me-1"></i> Ouvrir la messagerie</a>@endif</div>
<div class="row g-3 mb-4"><div class="col-6 col-lg-3"><div class="admin-kpi"><span>Achats boutique payés</span><strong>{{ number_format($classicTotal,2,',',' ') }} €</strong></div></div><div class="col-6 col-lg-3"><div class="admin-kpi"><span>Achats pro payés</span><strong>{{ number_format($professionalTotal,2,',',' ') }} €</strong></div></div><div class="col-6 col-lg-3"><div class="admin-kpi"><span>Commandes</span><strong>{{ $orders->total() }}</strong></div></div><div class="col-6 col-lg-3"><div class="admin-kpi"><span>Accès</span><strong>{{ $customer->blocked?'Bloqué':'Actif' }}</strong></div></div></div>
<div class="admin-surface mb-4"><h2 class="h5">Profil et accès</h2><p class="small text-secondary">Le mot de passe reste confidentiel et n’est jamais affiché dans l’administration.</p><form method="post" action="{{ route('admin.customers.update',$customer) }}">@csrf @method('patch')<div class="row g-3"><div class="col-md-6"><label class="form-label">Nom complet</label><input class="form-control" name="name" value="{{ old('name',$customer->name) }}" required></div><div class="col-md-6"><label class="form-label">E-mail</label><input class="form-control" type="email" name="email" value="{{ old('email',$customer->email) }}" required></div><div class="col-md-6"><label class="form-label">Téléphone</label><input class="form-control" name="phone" value="{{ old('phone',$customer->phone) }}"></div><div class="col-md-6"><label class="form-label">Type d’accès</label><select class="form-select" name="role"><option value="customer" @selected($customer->role==='customer')>Client classique</option><option value="reseller" @selected($customer->role==='reseller')>Revendeur professionnel validé</option></select></div><div class="col-12"><label class="form-label">Adresse</label><textarea class="form-control" name="address" rows="2">{{ old('address',$customer->address) }}</textarea></div><div class="col-12"><label class="form-label">Notes internes</label><textarea class="form-control" name="admin_notes" rows="3">{{ old('admin_notes',$customer->admin_notes) }}</textarea></div><div class="col-12 d-flex flex-wrap align-items-center gap-3"><div class="form-check form-switch"><input class="form-check-input" type="checkbox" name="blocked" value="1" id="blocked" @checked($customer->blocked)><label class="form-check-label" for="blocked">Bloquer les connexions</label></div><button class="btn btn-dark ms-md-auto">Enregistrer le profil</button></div></div></form></div>
<div class="admin-surface mb-4"><h2 class="h5">Historique des commandes boutique</h2><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Commande</th><th>Date</th><th>Paiement</th><th>État</th><th>Total</th></tr></thead><tbody>@forelse($orders as $order)<tr><td>#{{ $order->id }}</td><td>{{ $order->created_at->format('d/m/Y') }}</td><td>{{ $order->payment_status }}</td><td>{{ $order->status }}</td><td>{{ number_format($order->total,2,',',' ') }} €</td></tr>@empty<tr><td colspan="5">Aucune commande.</td></tr>@endforelse</tbody></table></div>{{ $orders->links() }}</div>
@if($customer->resellerRequest)<div class="admin-surface"><h2 class="h5">Dossier et historique professionnel</h2><p><strong>{{ $customer->resellerRequest->business_name }}</strong> · SIRET {{ $customer->resellerRequest->siret }} · {{ $customer->resellerRequest->status }}</p><div class="table-responsive"><table class="table"><thead><tr><th>Commande pro</th><th>Paiement</th><th>État</th><th>Total TTC</th></tr></thead><tbody>@forelse($professionalOrders as $order)<tr><td>#{{ $order->id }}</td><td>{{ $order->payment_status }}</td><td>{{ $order->status }}</td><td>{{ number_format($order->total_ttc,2,',',' ') }} €</td></tr>@empty<tr><td colspan="4">Aucune commande professionnelle.</td></tr>@endforelse</tbody></table></div>{{ $professionalOrders->links() }}<h3 class="h6 mt-4">Précommandes permanentes</h3><ul class="list-group list-group-flush">@forelse($preorders as $preorder)<li class="list-group-item px-0 d-flex justify-content-between"><span>{{ $preorder->product?->name }}</span><strong>{{ $preorder->status }}</strong></li>@empty<li class="list-group-item px-0">Aucune précommande.</li>@endforelse</ul></div>@endif
@endsection
