@extends('layouts.admin')
@section('title', 'Revendeurs - Administration AchatHub')
@section('admin-content')
<div class="d-flex justify-content-between align-items-center mb-4"><div><span class="text-secondary small text-uppercase">Administration B2B</span><h1 class="h2 fw-bold mb-0">Revendeurs et présentoirs</h1></div></div>

<h2 class="h4 fw-bold">Demandes d’accès</h2>
<div class="table-responsive border rounded mb-5"><table class="table align-middle mb-0"><thead class="table-light"><tr><th>Commerce</th><th>Compte</th><th>Formule</th><th>Statut</th><th>Décision</th></tr></thead><tbody>
@forelse($requests as $request)
<tr><td><strong>{{ $request->business_name }}</strong><br><small class="text-secondary">{{ $request->legal_form ?: $request->business_type }} · {{ $request->city }}<br>@if($request->siret)SIRET {{ $request->siret }}<br>@endif{{ $request->phone }}</small></td><td>@if($request->user){{ $request->user->name }}<br><small>{{ $request->user->email }}</small>@else<span class="text-danger">Ancienne demande sans compte</span>@endif</td><td>{{ $request->formula }}<br><small>{{ $request->display_type }}</small></td><td><span class="badge {{ $request->status === 'Approuvée' ? 'text-bg-success' : ($request->status === 'En attente' ? 'text-bg-warning' : 'text-bg-danger') }}">{{ $request->status }}</span></td><td>@if($request->user)<form method="post" action="{{ route('admin.resellers.review',$request) }}" class="d-flex flex-column gap-2">@csrf @method('patch')<select class="form-select form-select-sm" name="status"><option value="Approuvée">Approuver</option><option value="Refusée">Refuser</option><option value="Suspendue">Suspendre</option></select><input class="form-control form-control-sm" name="admin_notes" placeholder="Note interne ou motif"><button class="btn btn-sm btn-dark">Enregistrer la décision</button></form>@endif</td></tr>
@empty<tr><td colspan="5" class="text-center text-secondary p-4">Aucune demande.</td></tr>@endforelse
</tbody></table></div>{{ $requests->links() }}

<h2 class="h4 fw-bold mt-5">Précommandes de produits</h2>
<div class="table-responsive border rounded mb-5"><table class="table align-middle mb-0"><thead class="table-light"><tr><th>Demande</th><th>Revendeur</th><th>Produit</th><th>Traitement</th></tr></thead><tbody>@forelse($preorders as $preorder)<tr><td><strong>{{ $preorder->number }}</strong><br><small>{{ $preorder->created_at->format('d/m/Y H:i') }}</small></td><td>{{ $preorder->user->name }}<br><small>{{ $preorder->user->email }}</small></td><td><div class="d-flex align-items-center gap-2"><img src="{{ $preorder->product->image }}" width="50" height="50" style="object-fit:contain" alt=""><span>{{ $preorder->product->name }}<small class="d-block text-secondary">{{ $preorder->product->sku }}</small></span></div></td><td><form method="post" action="{{ route('admin.professional-preorders.update',$preorder) }}" class="d-flex gap-2">@csrf @method('patch')<select class="form-select form-select-sm" name="status">@foreach(['Nouvelle','En cours','Validée','Refusée','Terminée'] as $status)<option @selected($preorder->status===$status)>{{ $status }}</option>@endforeach</select><input class="form-control form-control-sm" name="admin_notes" value="{{ $preorder->admin_notes }}" placeholder="Réponse visible par le revendeur"><button class="btn btn-sm btn-dark">Enregistrer</button></form></td></tr>@empty<tr><td colspan="4" class="text-center text-secondary p-4">Aucune précommande.</td></tr>@endforelse</tbody></table></div>

<h2 class="h4 fw-bold mt-5">Offres de présentoirs</h2>
<div class="row g-3 mb-5">@foreach($displays as $display)<div class="col-lg-4"><form method="post" action="{{ route('admin.displays.update',$display) }}" class="card h-100"><div class="card-body">@csrf @method('patch')<h3 class="h6 fw-bold">{{ $display->name }}</h3><p class="small text-secondary">{{ $display->products_count }} références</p><label class="form-label">Prix professionnel HT</label><div class="input-group"><input class="form-control" name="wholesale_price_ht" type="number" step="0.01" min="0" value="{{ $display->wholesale_price_ht }}"><span class="input-group-text">€</span></div><div class="form-check form-switch mt-3"><input type="hidden" name="active" value="0"><input class="form-check-input" type="checkbox" name="active" value="1" @checked($display->active)><label class="form-check-label">Offre visible</label></div></div><div class="card-footer bg-white"><button class="btn btn-outline-dark w-100">Mettre à jour</button></div></form></div>@endforeach</div>

<div class="d-flex flex-wrap justify-content-between align-items-end gap-3 mt-5 mb-3"><div><h2 class="h4 fw-bold mb-1">Catalogue des produits grossistes</h2><p class="text-secondary mb-0">Prix HT, minimum de commande, stock et visibilité dans l’espace Pro.</p></div><form method="get" action="{{ route('admin.resellers') }}" class="d-flex gap-2"><input class="form-control" name="pro_q" value="{{ request('pro_q') }}" placeholder="Nom, SKU ou catégorie"><button class="btn btn-outline-dark">Rechercher</button></form></div>
<div class="table-responsive border rounded mb-3"><table class="table align-middle mb-0"><thead class="table-light"><tr><th>Produit</th><th>Catégorie</th><th>Prix HT</th><th>Minimum</th><th>Stock</th><th>Visible</th><th></th></tr></thead><tbody>
@forelse($professionalProducts as $product)
<tr><td><div class="d-flex align-items-center gap-2"><img src="{{ $product->image ?: asset('assets/category-accessoires.png') }}" width="48" height="48" style="object-fit:contain" alt=""><span><strong>{{ $product->name }}</strong><small class="d-block text-secondary">{{ $product->sku }}</small></span></div></td><td><input form="professional-product-{{ $product->id }}" class="form-control form-control-sm" name="category" value="{{ $product->category }}" required></td><td><div class="input-group input-group-sm"><input form="professional-product-{{ $product->id }}" class="form-control" name="wholesale_price_ht" type="number" step="0.01" min="0" value="{{ $product->wholesale_price_ht }}" required><span class="input-group-text">€</span></div></td><td><input form="professional-product-{{ $product->id }}" class="form-control form-control-sm" style="min-width:85px" name="minimum_order_quantity" type="number" min="1" value="{{ $product->minimum_order_quantity }}" required></td><td><input form="professional-product-{{ $product->id }}" class="form-control form-control-sm" style="min-width:85px" name="stock" type="number" min="0" value="{{ $product->stock }}" required></td><td><div class="form-check form-switch"><input form="professional-product-{{ $product->id }}" type="hidden" name="active" value="0"><input form="professional-product-{{ $product->id }}" class="form-check-input" type="checkbox" name="active" value="1" @checked($product->active) aria-label="Produit visible"></div></td><td><form id="professional-product-{{ $product->id }}" method="post" action="{{ route('admin.professional-products.update',$product) }}">@csrf @method('patch')<button class="btn btn-sm btn-dark">Enregistrer</button></form></td></tr>
@empty<tr><td colspan="7" class="text-center text-secondary p-4">Aucun produit professionnel.</td></tr>@endforelse
</tbody></table></div>{{ $professionalProducts->links() }}

<h2 class="h4 fw-bold">Commandes professionnelles</h2>
<div class="table-responsive border rounded"><table class="table align-middle mb-0"><thead class="table-light"><tr><th>Commande</th><th>Revendeur</th><th>Total TTC</th><th>Suivi</th></tr></thead><tbody>@forelse($orders as $order)<tr><td><strong>{{ $order->number }}</strong><br><small>{{ $order->created_at->format('d/m/Y H:i') }}</small></td><td>{{ $order->user->name }}<br><small>{{ $order->city }}</small></td><td>{{ number_format($order->total_ttc,2,',',' ') }} €</td><td><form method="post" action="{{ route('admin.professional-orders.update',$order) }}" class="d-flex gap-2">@csrf @method('patch')<select class="form-select form-select-sm" name="status">@foreach(['Nouvelle','Confirmée','En préparation','Expédiée','Livrée','Annulée'] as $status)<option @selected($order->status===$status)>{{ $status }}</option>@endforeach</select><select class="form-select form-select-sm" name="payment_status">@foreach(['En attente','Payé','Remboursé'] as $payment)<option @selected($order->payment_status===$payment)>{{ $payment }}</option>@endforeach</select><button class="btn btn-sm btn-dark">Enregistrer</button></form></td></tr>@empty<tr><td colspan="4" class="text-center text-secondary p-4">Aucune commande professionnelle.</td></tr>@endforelse</tbody></table></div>
@endsection
