@extends('layouts.app') @section('title','Politique de confidentialité - AchatHub') @section('content')
<div class="legal-page"><header><span>RGPD</span><h1>Politique de confidentialité</h1><p>Nous expliquons clairement quelles données sont utilisées et pourquoi.</p></header>
<section><h2>Responsable du traitement</h2><p>{{ $settings['legal_name'] ?? 'AchatHub' }}, {{ $settings['company_address'] ?? '' }}. Contact : {{ $settings['support_email'] ?? 'contact@achathub.fr' }}.</p></section>
<section><h2>Données collectées</h2><p>Identité, coordonnées, adresses, informations d’entreprise, commandes, paiements et statuts de paiement, échanges avec le support, préférences, données techniques de connexion et consentement aux cookies. AchatHub ne conserve pas les numéros complets de carte bancaire.</p></section>
<section><h2>Finalités et bases légales</h2><p>Exécution des commandes et du compte, obligations comptables et fiscales, prévention de la fraude, support client, gestion des revendeurs et, avec consentement lorsque nécessaire, mesure d’audience ou communication commerciale.</p></section>
<section><h2>Destinataires et transferts</h2><p>Les données sont accessibles aux équipes habilitées et aux prestataires indispensables de paiement, hébergement et livraison, dans la limite de leur mission. Tout transfert hors Espace économique européen doit être encadré par une garantie reconnue.</p></section>
<section><h2>Conservation</h2><p>Le compte actif est conservé pendant la relation commerciale. Les pièces de commande et facturation sont conservées selon les obligations légales, généralement dix ans. Les demandes et échanges sont conservés le temps nécessaire à leur traitement et à la défense des droits.</p></section>
<section><h2>Vos droits</h2><p>Vous disposez des droits d’accès, rectification, effacement, limitation, opposition et portabilité, ainsi que du droit de saisir la CNIL. Depuis votre compte, ouvrez « Mes données et droits » pour transmettre une demande sécurisée.</p></section></div>
@endsection
