@extends('layouts.app') @section('title','Conditions générales - AchatHub') @section('content')
<div class="legal-page"><header><span>INFORMATIONS CONTRACTUELLES</span><h1>Conditions générales d’utilisation et de vente</h1><p>Version du 15 juillet 2026</p></header>
<section><h2>1. Objet</h2><p>Ces conditions encadrent l’utilisation d’AchatHub, les achats des clients particuliers et l’accès au programme professionnel. L’identité complète de l’exploitant est indiquée dans les mentions légales.</p></section>
<section><h2>2. Compte et sécurité</h2><p>Chaque utilisateur fournit des informations exactes et protège ses identifiants. Les accès classiques et professionnels sont distincts. AchatHub peut suspendre un compte en cas de fraude, d’impayé ou d’usage abusif, après vérification.</p></section>
<section><h2>3. Produits, prix et paiement</h2><p>Les prix, caractéristiques et disponibilités sont affichés avant validation. Une commande n’est définitive qu’après confirmation. Les moyens proposés peuvent inclure carte bancaire, paiement à la livraison ou autre moyen explicitement affiché.</p></section>
<section><h2>4. Commandes et précommandes professionnelles</h2><p>Une précommande exprime une demande professionnelle et ne vaut pas automatiquement acceptation. Après validation, une commande reste conservée dans l’historique comptable et commercial : elle ne peut pas être supprimée par le client. Une annulation ou un remboursement apparaît par changement de statut.</p></section>
<section><h2>5. Livraison, rétractation et garanties</h2><p>Les délais sont communiqués pendant la commande. Les consommateurs bénéficient des droits de rétractation et garanties légales applicables, sous réserve des exceptions prévues par la loi. Les conditions propres aux professionnels sont précisées lors de l’offre.</p></section>
<section><h2>6. Responsabilité et litiges</h2><p>AchatHub met en œuvre les moyens raisonnables pour assurer la disponibilité du service. En cas de difficulté, contactez le support depuis la messagerie sécurisée afin de rechercher une solution amiable.</p></section></div>
@endsection
