@extends('layouts.app')
@section('title', request('q') ? 'Recherche '.request('q').' - AchatHub' : 'AchatHub - Boutique en ligne')
@section('content')
@if(!request()->hasAny(['q','category','family','subcategory','brand','min_price','max_price','sort','page']))
<section class="hero"><div class="container"><span class="badge text-bg-light mb-3">Nouveautés et prix promotionnels</span><h1>{{ $heroTitle }}</h1><p class="lead col-lg-6 mt-3">{{ $heroText }}</p><a href="#catalogue" class="btn btn-ah btn-lg mt-2">Voir le catalogue</a><a href="{{ route('reseller.index') }}" class="btn btn-outline-light btn-lg mt-2 ms-sm-2">Solutions professionnelles</a></div></section>
<section class="store-confidence" aria-label="Services AchatHub"><div class="container store-confidence-grid"><div class="store-confidence-item"><i class="bi bi-box-seam"></i><span><strong>Stock visible</strong><small>Disponibilité indiquée sur chaque produit</small></span></div><div class="store-confidence-item"><i class="bi bi-shield-check"></i><span><strong>Paiement sécurisé</strong><small>Commande protégée de bout en bout</small></span></div><div class="store-confidence-item"><i class="bi bi-receipt"></i><span><strong>Facture disponible</strong><small>Depuis votre espace client</small></span></div><div class="store-confidence-item"><i class="bi bi-chat-dots"></i><span><strong>Support AchatHub</strong><small>Une messagerie simple pour vos demandes</small></span></div></div></section>
<section class="container py-4 py-lg-5"><div class="category-shortcuts">@foreach($categories->take(6) as $category)<a href="{{ route('home',['category'=>$category->slug]) }}"><span class="category-shortcut-icon"><i class="bi bi-grid"></i></span><strong>{{ $category->name }}</strong><small>{{ number_format($category->products_count, 0, ',', ' ') }} produits</small></a>@endforeach</div></section>
@endif
<section id="catalogue" class="container py-4">
    <nav class="catalog-breadcrumb mb-3"><a href="{{ route('home') }}">Accueil</a>@if($selectedCategory)<i class="bi bi-chevron-right"></i>@if($selectedCategory->parent)<a href="{{ route('home',['category'=>$selectedCategory->parent->slug]) }}">{{ $selectedCategory->parent->name }}</a><i class="bi bi-chevron-right"></i>@endif<span>{{ $selectedCategory->name }}</span>@endif @if(request('family'))<i class="bi bi-chevron-right"></i><span>{{ request('family') }}</span>@endif</nav>
    <div class="catalog-heading"><div><div class="catalog-eyebrow">Catalogue AchatHub</div><h1>{{ request('q') ? 'Résultats pour « '.request('q').' »' : $catalogTitle }}</h1><p>{{ number_format($products->total(), 0, ',', ' ') }} produit(s) trouvé(s)</p></div><div class="catalog-actions"><button class="btn btn-outline-dark d-lg-none" type="button" data-bs-toggle="offcanvas" data-bs-target="#catalogFilters"><i class="bi bi-sliders"></i> Filtrer</button><form action="{{ route('home') }}" data-catalog-sort>@foreach(request()->except(['sort','page']) as $key => $value)@if(is_scalar($value))<input type="hidden" name="{{ $key }}" value="{{ $value }}">@endif @endforeach<label class="visually-hidden" for="catalog-sort">Trier les produits</label><select id="catalog-sort" class="form-select" name="sort" onchange="this.form.submit()"><option value="">Pertinence</option><option value="newest" @selected(request('sort')==='newest')>Nouveautés</option><option value="price_asc" @selected(request('sort')==='price_asc')>Prix croissant</option><option value="price_desc" @selected(request('sort')==='price_desc')>Prix décroissant</option><option value="discount" @selected(request('sort')==='discount')>Meilleures promotions</option><option value="rating" @selected(request('sort')==='rating')>Mieux notés</option></select></form></div></div>
    @if(request()->hasAny(['category','family','subcategory','brand','min_price','max_price','in_stock']))<div class="catalog-filter-summary mb-3">@if($selectedCategory)<span>{{ $selectedCategory->name }}</span>@endif @if(request('family'))<span>{{ request('family') }}</span>@endif @if(request('subcategory'))<span>{{ request('subcategory') }}</span>@endif @if(request('brand'))<span>{{ request('brand') }}</span>@endif @if(request('min_price'))<span>Dès {{ request('min_price') }} €</span>@endif @if(request('max_price'))<span>Jusqu’à {{ request('max_price') }} €</span>@endif @if(request('in_stock'))<span>En stock</span>@endif<a href="{{ route('home') }}">Tout effacer</a></div>@endif
    <div class="row g-4">
        <aside class="col-lg-3 d-none d-lg-block">@include('store.partials.filters', ['filterId' => 'desktop'])</aside>
        <div class="col-lg-9"><div class="row row-cols-2 row-cols-md-3 row-cols-xl-4 g-3 catalog-product-grid" data-product-grid>@forelse($products as $product)<div class="col"><x-product-card :product="$product" /></div>@empty<div class="col-12"><div class="catalog-empty"><i class="bi bi-search"></i><h2>Aucun produit trouvé</h2><p>Essayez une autre référence, une marque ou retirez certains filtres.</p><a class="btn btn-dark" href="{{ route('home') }}">Voir tout le catalogue</a></div></div>@endforelse</div>
        @if($products->hasMorePages())<div class="catalog-load-more"><a class="btn btn-outline-dark btn-lg" href="{{ $products->nextPageUrl() }}" data-load-more><i class="bi bi-plus-lg"></i><span>Afficher plus de produits</span></a><small>Page {{ $products->currentPage() }} sur {{ $products->lastPage() }}</small></div>@endif
        <div class="d-none d-lg-block mt-4">{{ $products->links() }}</div></div>
    </div>
</section>
<div class="offcanvas offcanvas-start catalog-filter-offcanvas" tabindex="-1" id="catalogFilters" aria-labelledby="catalogFiltersTitle"><div class="offcanvas-header"><h2 class="h5 mb-0" id="catalogFiltersTitle">Filtrer les produits</h2><button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Fermer"></button></div><div class="offcanvas-body">@include('store.partials.filters', ['filterId' => 'mobile'])</div></div>
@endsection
@push('scripts')<script src="{{ asset('js/catalog.js') }}?v=20260802b" defer></script>@endpush
