@extends('layouts.app')
@section('title', $product->name.' | AchatHub')
@section('meta_description', $productSeoDescription)
@section('canonical', \App\Support\Seo::root().route('products.show', $product, false))
@section('og_type', 'product')
@section('og_image', \App\Support\Seo::absoluteUrl($gallery->first() ?: '/assets/category-accessoires.webp?v=20260802b'))
@push('structured-data')
    <x-structured-data :data="$productStructuredData" />
    <x-structured-data :data="$productBreadcrumbData" />
@endpush
@section('content')
<div class="container product-page py-4 py-lg-5">
    <nav class="catalog-breadcrumb mb-4"><a href="{{ route('home') }}">Accueil</a><i class="bi bi-chevron-right"></i><a href="{{ route('home',['category'=>$product->category->slug]) }}">{{ $product->category->name }}</a>@if($product->family)<i class="bi bi-chevron-right"></i><a href="{{ route('home',['category'=>$product->category->slug,'family'=>str($product->family)->before('>')->trim()]) }}">{{ str($product->family)->before('>')->trim() }}</a>@endif</nav>
    <div class="row g-4 g-lg-5">
        <div class="col-lg-6"><div class="product-gallery"><div class="product-gallery-main"><img data-gallery-main src="{{ $gallery->first() ?: asset('assets/category-accessoires.webp').'?v=20260802b' }}" alt="{{ $product->name }}" decoding="async"></div>@if($gallery->count()>1)<div class="product-thumbnails" aria-label="Photos du produit">@foreach($gallery as $image)<button type="button" class="{{ $loop->first ? 'active' : '' }}" data-gallery-image="{{ $image }}" aria-label="Afficher la photo {{ $loop->iteration }}"><img src="{{ $image }}" alt="" loading="lazy" decoding="async"></button>@endforeach</div>@endif</div></div>
        <div class="col-lg-6"><div class="product-purchase-panel">@if($product->discount)<span class="badge discount mb-3">-{{ $product->discount }} %</span>@endif @if($product->brand)<div class="product-brand">{{ $product->brand }}</div>@endif<h1>{{ $product->name }}</h1><div class="product-meta"><span>Réf. {{ $product->sku }}</span><span>{{ $product->condition }}</span></div>@if($product->reviews_count)<a href="#avis" class="product-rating-link"><span class="product-stars">@for($star=1;$star<=5;$star++)<i class="bi {{ $star <= round($product->rating) ? 'bi-star-fill' : 'bi-star' }}"></i>@endfor</span><strong>{{ number_format($product->rating,1,',',' ') }}</strong><span>{{ $product->reviews_count }} avis</span></a>@endif
        @if($product->model)<div class="compatibility-note"><i class="bi bi-check-circle-fill"></i><span><strong>Compatibilité indiquée</strong><small>{{ $product->model }}</small></span></div>@endif
        <div class="product-price-block"><span class="price">{{ number_format($product->price,2,',',' ') }} € <small>TTC</small></span>@if($product->old_price)<span class="old-price">{{ number_format($product->old_price,2,',',' ') }} €</span><small>Vous économisez {{ number_format($product->old_price-$product->price,2,',',' ') }} €</small>@endif</div>
        <div class="product-stock {{ $product->stock ? 'available' : 'unavailable' }}"><i class="bi {{ $product->stock ? 'bi-check-circle-fill' : 'bi-x-circle-fill' }}"></i><span><strong>{{ $product->stock ? 'En stock' : 'Produit épuisé' }}</strong>@if($product->stock)<small>Expédition prévue sous 24 à 48 h</small>@endif</span></div>
        <p class="product-description">{{ $product->description ?: 'Produit sélectionné par AchatHub pour sa qualité et son utilité au quotidien.' }}</p>
        <form method="post" action="{{ route('cart.add',$product) }}" class="product-buy-form js-add-to-cart">@csrf<div class="product-quantity"><label for="product-quantity">Quantité</label><input id="product-quantity" class="form-control" type="number" name="quantity" value="1" min="1" max="{{ $product->stock }}"></div><button class="btn btn-ah btn-lg" {{ !$product->stock?'disabled':'' }}><i class="bi bi-cart-plus"></i><span>Ajouter au panier</span></button></form>
        <form method="post" action="{{ route('cart.buy-now',$product) }}" class="mt-2">@csrf<input type="hidden" name="quantity" value="1" data-buy-now-quantity><button class="btn btn-dark btn-lg w-100" {{ !$product->stock?'disabled':'' }}><i class="bi bi-lightning-charge"></i> Acheter maintenant</button></form>
        <div class="product-reassurance"><div><i class="bi bi-truck"></i><span><strong>Livraison annoncée avant paiement</strong><small>Standard, point relais ou express</small></span></div><div><i class="bi bi-arrow-return-left"></i><span><strong>Retours depuis votre compte</strong><small>Suivi autonome de votre demande</small></span></div><div><i class="bi bi-shield-lock"></i><span><strong>Paiement sécurisé</strong><small>Vos informations restent protégées</small></span></div></div>
        @auth @if(auth()->user()->role==='customer')<form method="post" action="{{ route('wishlist.toggle',$product) }}">@csrf<button class="btn btn-outline-dark w-100"><i class="bi bi-heart"></i> Ajouter ou retirer des favoris</button></form>@endif @endauth</div></div>
    </div>
    @if($product->features)<section class="product-information"><h2>Caractéristiques</h2><div class="product-feature-grid">@foreach($product->features as $feature)<div><i class="bi bi-check2"></i><span>{{ $feature }}</span></div>@endforeach</div></section>@endif
    <section class="product-reviews-section" id="avis"><div class="section-heading"><div><small>AVIS CLIENTS</small><h2>Ce qu’en pensent nos clients</h2></div>@if($product->reviews_count)<div class="review-score"><strong>{{ number_format($product->rating,1,',',' ') }}/5</strong><span>{{ $product->reviews_count }} avis vérifié(s)</span></div>@endif</div>
        @if($canReview)<form class="review-form" method="post" action="{{ route('products.reviews.store',$product) }}">@csrf<h3>Donnez votre avis sur ce produit</h3><div class="row g-3"><div class="col-sm-4"><label class="form-label">Votre note</label><select class="form-select" name="rating" required>@foreach([5,4,3,2,1] as $rating)<option value="{{ $rating }}">{{ $rating }} / 5</option>@endforeach</select></div><div class="col-sm-8"><label class="form-label">Titre <span class="text-secondary">(facultatif)</span></label><input class="form-control" name="title" maxlength="120"></div><div class="col-12"><label class="form-label">Votre expérience</label><textarea class="form-control" name="comment" minlength="10" maxlength="2000" rows="3" required></textarea></div><div class="col-12"><button class="btn btn-dark">Publier mon avis vérifié</button></div></div></form>@endif
        <div class="review-list">@forelse($product->reviews as $review)<article><div class="review-head"><div><strong>{{ $review->user->name }}</strong><span><i class="bi bi-patch-check-fill"></i> Achat vérifié</span></div><time>{{ $review->created_at->translatedFormat('j F Y') }}</time></div><div class="product-stars">@for($star=1;$star<=5;$star++)<i class="bi {{ $star <= $review->rating ? 'bi-star-fill' : 'bi-star' }}"></i>@endfor</div>@if($review->title)<h3>{{ $review->title }}</h3>@endif<p>{{ $review->comment }}</p></article>@empty<div class="review-empty"><i class="bi bi-chat-square-text"></i><p>Aucun avis publié pour le moment.</p></div>@endforelse</div>
    </section>
    @if($similarProducts->isNotEmpty())<section class="similar-products"><div class="section-heading"><div><small>À DÉCOUVRIR</small><h2>Produits similaires</h2></div></div><div class="row row-cols-2 row-cols-md-4 g-3">@foreach($similarProducts as $similar)<div class="col"><x-product-card :product="$similar" /></div>@endforeach</div></section>@endif
</div>
@endsection
@push('scripts')<script src="{{ asset('js/product.js') }}?v=20260802b" defer></script>@endpush
