@extends('layouts.checkout')
@section('title', 'Commande '.$order->number.' confirmée - AchatHub')
@section('content')
<div class="container order-confirmation py-5">
    <div class="text-center mb-4"><div class="confirmation-mark"><i class="bi bi-check-lg"></i></div><h1 class="h2 fw-bold">Merci, votre commande est confirmée</h1><p class="text-secondary">Un récapitulatif sera envoyé à <strong>{{ $order->guest_email }}</strong>.</p><span class="order-reference">{{ $order->number }}</span></div>
    <section class="checkout-section"><h2 class="h5 fw-bold">Suivi de votre commande</h2>@include('components.order-timeline', ['order' => $order])<div class="row g-3"><div class="col-md-6"><div class="p-3 bg-light h-100"><small class="text-secondary">Livraison estimée</small><strong class="d-block">{{ $order->estimated_delivery_date?->translatedFormat('l j F Y') ?? 'Date à confirmer' }}</strong><span>{{ $order->shipping_name }}<br>{{ $order->shipping_address }}<br>{{ $order->shipping_postal_code }} {{ $order->shipping_city }}</span></div></div><div class="col-md-6"><div class="p-3 bg-light h-100"><small class="text-secondary">Paiement</small><strong class="d-block">{{ ['card' => 'Carte bancaire', 'livraison' => 'Paiement à la livraison', 'virement' => 'Virement bancaire', 'mobile' => 'Paiement mobile'][$order->payment_method] ?? ucfirst($order->payment_method) }}</strong><span>Statut : {{ $order->payment_status }}</span>@if($order->tracking_number)<hr><small class="text-secondary">Suivi {{ $order->carrier }}</small><strong class="d-block">{{ $order->tracking_number }}</strong>@endif</div></div></div></section>
    <section class="checkout-section"><h2 class="h5 fw-bold mb-3">Détail</h2>@foreach($order->items as $item)<div class="d-flex justify-content-between gap-3 py-2 border-bottom"><span>{{ $item->quantity }} × {{ $item->name }}</span><strong class="text-nowrap">{{ number_format($item->price * $item->quantity, 2, ',', ' ') }} €</strong></div>@endforeach<div class="d-flex justify-content-between pt-3 fs-5"><strong>Total TTC</strong><strong>{{ number_format($order->total, 2, ',', ' ') }} €</strong></div></section>
    @guest<div class="checkout-section text-center"><h2 class="h5 fw-bold">Retrouvez plus facilement vos prochaines commandes</h2><p class="text-secondary">Créez votre compte AchatHub avec la même adresse e-mail.</p><a class="btn btn-outline-dark" href="{{ route('register') }}">Créer mon compte</a></div>@endguest
    <div class="d-flex flex-wrap justify-content-center gap-2"><a class="btn btn-ah" href="{{ route('home') }}">Continuer mes achats</a><a class="btn btn-outline-dark" href="{{ route('support.index') }}">Besoin d’aide</a></div>
</div>
@endsection
