<!doctype html>
<html lang="fr">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="csrf-token" content="{{ csrf_token() }}">
    @include('components.seo-head')
    @include('components.brand-head')
    @if(request()->routeIs('home'))<link rel="preload" href="{{ asset('assets/achathub-hero-accessoires.webp') }}?v=20260802b" as="image" type="image/webp" fetchpriority="high">@endif
    <link href="{{ asset('vendor/bootstrap/bootstrap.min.css') }}?v=5.3.8" rel="stylesheet"><link href="{{ asset('vendor/bootstrap-icons/bootstrap-icons.min.css') }}?v=1.11.3" rel="stylesheet"><link href="{{ asset('css/achathub.css') }}?v=20260802b" rel="stylesheet"><link href="{{ asset('css/achathub-nav.css') }}?v=20260802b" rel="stylesheet"><link href="{{ asset('css/achathub-commerce.css') }}?v=20260802b" rel="stylesheet"><link href="{{ asset('css/achathub-auth.css') }}?v=20260802b" rel="stylesheet"><link href="{{ asset('css/achathub-management.css') }}?v=20260802b" rel="stylesheet"><link href="{{ asset('css/achathub-speed-commerce.css') }}?v=20260802b" rel="stylesheet"><link href="{{ asset('css/achathub-design.css') }}?v=20260803a" rel="stylesheet">
</head>
<body class="@yield('body-class')">
@include('components.brand-loader')
@php
    $shopCartCount = collect(session('cart', []))->sum();
    $accountRoute = auth()->check() ? (auth()->user()->role === 'admin' ? route('admin.index') : (auth()->user()->role === 'reseller' ? route('pro.account') : route('account.index'))) : route('login');
    $proEntryRoute = auth()->check() && auth()->user()->role === 'reseller' ? route('pro.index') : (auth()->guest() ? route('professional.login') : route('reseller.index'));
@endphp
<div class="topbar py-2"><div class="container d-flex justify-content-between"><span>Livraison rapide · Paiement sécurisé · Prix promotionnels</span><a class="text-white text-decoration-none" href="{{ auth()->check()?route('messages.index'):route('support.index') }}">Support AchatHub</a></div></div>
<header class="navbar-shop sticky-top"><div class="container py-2 py-lg-3"><div class="shop-header-grid"><a href="{{ route('home') }}" class="shop-brand" aria-label="Accueil AchatHub"><img src="{{ asset('assets/achathub-logo.webp') }}?v=20260803b" class="brand-mark" width="46" height="41" alt=""><span class="brand-name">AchatHub</span></a><form action="{{ route('home') }}" class="shop-search"><input class="form-control search-control" name="q" value="{{ request('q') }}" placeholder="Rechercher un produit, une marque, une référence" aria-label="Rechercher dans la boutique"><button class="shop-search-button" aria-label="Rechercher"><i class="bi bi-search"></i></button></form><nav class="shop-header-actions d-none d-lg-flex" aria-label="Accès rapides"><a href="{{ $accountRoute }}"><i class="bi bi-person"></i><span>Compte</span></a><a href="{{ $proEntryRoute }}"><i class="bi bi-briefcase"></i><span>Pro</span></a><a class="shop-header-cart" href="{{ route('cart.index') }}"><i class="bi bi-cart3"></i><span>Panier</span><b data-cart-count>{{ $shopCartCount }}</b></a></nav><button class="shop-menu-button" type="button" data-bs-toggle="offcanvas" data-bs-target="#shopMainMenu" aria-controls="shopMainMenu" aria-label="Ouvrir le menu"><i class="bi bi-list"></i></button></div></div>
<nav class="shop-category-bar" aria-label="Navigation des catégories"><div class="container d-flex align-items-center gap-2"><button class="category-open-button" type="button" data-bs-toggle="offcanvas" data-bs-target="#shopCategoryMenu"><i class="bi bi-grid"></i><span>Catégories</span></button><a class="shop-quick-link" href="{{ route('home') }}">Tous les produits</a>@foreach($menuCategories->take(5) as $quickCategory)<a class="shop-quick-link d-none d-lg-inline-flex {{ request('category')===$quickCategory->slug?'active':'' }}" href="{{ route('home',['category'=>$quickCategory->slug]) }}">{{ $quickCategory->name }}</a>@endforeach</div></nav></header>

<div class="offcanvas offcanvas-end shop-main-menu" tabindex="-1" id="shopMainMenu" aria-labelledby="shopMainMenuTitle"><div class="offcanvas-header"><div><small>ACHATHUB</small><h2 class="h4 mb-0" id="shopMainMenuTitle">Menu</h2></div><button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Fermer"></button></div><div class="offcanvas-body d-flex flex-column"><nav class="shop-menu-links" aria-label="Menu principal">
<a href="{{ $accountRoute }}"><i class="bi bi-person"></i><span><strong>{{ auth()->check() ? 'Mon compte' : 'Connexion client' }}</strong><small>Commandes, favoris et informations</small></span><i class="bi bi-chevron-right ms-auto"></i></a>
<a href="{{ route('cart.index') }}"><i class="bi bi-cart3"></i><span><strong>Mon panier</strong><small data-cart-summary>{{ $shopCartCount }} article(s) dans le panier</small></span><b class="menu-count" data-cart-count>{{ $shopCartCount }}</b></a>
@if(auth()->check() && auth()->user()->role === 'reseller')<a href="{{ route('pro.index') }}"><i class="bi bi-briefcase"></i><span><strong>Espace AchatHub Pro</strong><small>Catalogue et présentoirs professionnels</small></span><i class="bi bi-chevron-right ms-auto"></i></a>@elseif(auth()->guest())<a href="{{ route('professional.login') }}"><i class="bi bi-briefcase"></i><span><strong>Connexion AchatHub Pro</strong><small>Accéder au compte professionnel</small></span><i class="bi bi-chevron-right ms-auto"></i></a>@else<a href="{{ route('reseller.index') }}"><i class="bi bi-shop-window"></i><span><strong>Devenir revendeur</strong><small>Présentoirs et programme professionnel</small></span><i class="bi bi-chevron-right ms-auto"></i></a>@endif
<button type="button" data-bs-dismiss="offcanvas" data-bs-toggle="offcanvas" data-bs-target="#shopCategoryMenu"><i class="bi bi-grid"></i><span><strong>Toutes les catégories</strong><small>Parcourir les familles de produits</small></span><i class="bi bi-chevron-right ms-auto"></i></button>
<a href="{{ auth()->check()?route('messages.index'):route('support.index') }}"><i class="bi bi-chat-dots"></i><span><strong>Support AchatHub</strong><small>Nous contacter et suivre les réponses</small></span><i class="bi bi-chevron-right ms-auto"></i></a></nav>@auth<form method="post" action="{{ route('logout') }}" class="mt-auto pt-3">@csrf<button class="shop-logout-button"><i class="bi bi-box-arrow-right"></i> Se déconnecter</button></form>@endauth</div></div>

<div class="offcanvas offcanvas-start shop-category-menu" tabindex="-1" id="shopCategoryMenu" aria-labelledby="shopCategoryMenuTitle"><div class="offcanvas-header"><div><small>CATALOGUE ACHATHUB</small><h2 class="h4 mb-0" id="shopCategoryMenuTitle">Toutes les catégories</h2></div><button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Fermer"></button></div><div class="offcanvas-body"><p class="category-menu-intro">Choisissez une catégorie ou une famille pour afficher directement les produits correspondants.</p><div class="category-menu-grid">
@forelse($menuCategories as $menuCategory)@php($families = $menuFamilyCounts->get($menuCategory->id, collect()))@php($subcategories = $menuSubcategories->get($menuCategory->id, collect()))<section class="category-menu-section"><div class="category-menu-heading"><a href="{{ route('home',['category'=>$menuCategory->slug]) }}">{{ $menuCategory->name }}</a><span>{{ $menuCategory->products_count }}</span></div><div class="category-family-links">@foreach($subcategories->take(6) as $subcategory)<a href="{{ route('home',['category'=>$subcategory->slug]) }}"><span>{{ $subcategory->name }}</span><small>{{ $subcategory->products_count }}</small></a>@endforeach @foreach($families->take(max(0,8-$subcategories->count())) as $family)<a href="{{ route('home',array_merge(['category'=>$menuCategory->slug],[$family->filter_type=>$family->menu_family])) }}"><span>{{ $family->menu_family }}</span><small>{{ $family->total }}</small></a>@endforeach</div><a class="category-view-all" href="{{ route('home',['category'=>$menuCategory->slug]) }}">Voir toute la catégorie <i class="bi bi-arrow-right"></i></a></section>@empty<p>Aucune catégorie n’est disponible.</p>@endforelse
</div></div></div>

@if(session('success'))<div class="container mt-3"><div class="alert alert-success mb-0">{{ session('success') }}</div></div>@endif @if(session('error'))<div class="container mt-3"><div class="alert alert-danger mb-0">{{ session('error') }}</div></div>@endif @if($errors->any())<div class="container mt-3"><div class="alert alert-danger mb-0"><strong>Vérifiez les informations :</strong> {{ $errors->first() }}</div></div>@endif
<main>@yield('content')</main>
<footer class="footer mt-5 py-5"><div class="container"><div class="row g-4"><div class="col-md-5"><div class="d-flex align-items-center gap-2 mb-2"><img src="{{ asset('assets/achathub-logo.webp') }}?v=20260803b" width="44" height="39" alt=""><h4 class="text-white fw-bold mb-0">AchatHub</h4></div><p>Tout acheter, au meilleur prix. Une boutique claire pour les particuliers et une solution de revente pour les professionnels.</p><a class="btn btn-outline-light btn-sm" href="{{ route('reseller.index') }}">Découvrir AchatHub Pro</a></div><div class="col-6 col-md-3"><h6 class="text-white">Boutique</h6><a class="d-block text-light text-decoration-none py-1" href="{{ route('home') }}">Catalogue</a><a class="d-block text-light text-decoration-none py-1" href="{{ route('cart.index') }}">Panier</a><a class="d-block text-light text-decoration-none py-1" href="{{ auth()->check() && auth()->user()->role !== 'reseller' ? route('account.orders') : route('login') }}">Suivi commande</a></div><div class="col-6 col-md-4"><h6 class="text-white">Aide et informations</h6><a class="d-block text-light text-decoration-none py-1" href="{{ auth()->check()?route('messages.index'):route('support.index') }}">Contacter le support</a><a class="d-block text-light text-decoration-none py-1" href="{{ route('professional.login') }}">Connexion professionnelle</a><a class="d-block text-light text-decoration-none py-1" href="{{ route('legal.privacy') }}">Confidentialité</a><a class="d-block text-light text-decoration-none py-1" href="{{ route('legal.terms') }}">Conditions générales</a><a class="d-block text-light text-decoration-none py-1" href="{{ route('legal.cookies') }}">Cookies</a><a class="d-block text-light text-decoration-none py-1" href="{{ route('legal.notice') }}">Mentions légales</a></div></div><hr class="border-secondary"><small>© {{ date('Y') }} AchatHub. Tous droits réservés.</small></div></footer>
<nav class="mobile-shop-nav d-md-none" aria-label="Navigation mobile"><a href="{{ route('home') }}" class="{{ request()->routeIs('home')?'active':'' }}"><i class="bi bi-house"></i><span>Accueil</span></a><button type="button" data-bs-toggle="offcanvas" data-bs-target="#shopCategoryMenu"><i class="bi bi-grid"></i><span>Catégories</span></button><a href="{{ $proEntryRoute }}" class="{{ request()->routeIs('reseller.*','professional.*','pro.*')?'active':'' }}"><i class="bi bi-briefcase"></i><span>Pro</span></a><a href="{{ route('cart.index') }}" class="mobile-cart-link {{ request()->routeIs('cart.*')?'active':'' }}"><i class="bi bi-cart3"></i><span>Panier</span><b data-cart-count class="{{ $shopCartCount ? '' : 'd-none' }}">{{ $shopCartCount }}</b></a><a href="{{ $accountRoute }}" class="{{ request()->routeIs('account.*','login')?'active':'' }}"><i class="bi bi-person"></i><span>Compte</span></a></nav>
<div class="offcanvas offcanvas-end instant-cart" tabindex="-1" id="instantCart" aria-labelledby="instantCartTitle"><div class="offcanvas-header"><div><small class="instant-cart-success"><i class="bi bi-check-circle-fill"></i> AJOUTÉ AU PANIER</small><h2 class="h4 mb-0" id="instantCartTitle">Votre panier</h2></div><button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Fermer"></button></div><div class="offcanvas-body d-flex flex-column"><div class="instant-cart-product"><img data-instant-cart-image src="" alt=""><div><a data-instant-cart-name href="#">Produit</a><span>Quantité dans le panier : <strong data-instant-cart-quantity>1</strong></span><b data-instant-cart-price></b></div></div><div class="instant-cart-total"><span>Sous-total</span><strong data-instant-cart-subtotal>0,00 €</strong></div><div class="mt-auto d-grid gap-2"><button class="btn btn-outline-dark" type="button" data-bs-dismiss="offcanvas">Continuer mes achats</button><a class="btn btn-ah btn-lg" href="{{ route('cart.index') }}">Voir mon panier</a><a class="btn btn-dark" href="{{ route('checkout.index') }}">Commander maintenant</a></div></div></div>
<div class="shop-toast" role="status" aria-live="polite" data-shop-toast></div>
@include('components.cookie-banner')<script src="{{ asset('vendor/bootstrap/bootstrap.bundle.min.js') }}?v=5.3.8" defer></script><script src="{{ asset('js/shop-cart.js') }}?v=20260802b" defer></script>@stack('scripts')
</body></html>
