@extends('layouts.pro')
@section('title', 'Validation et paiement - AchatHub Pro')
@section('pro-content')
<div class="pro-page-head"><div><h1>Livraison et paiement</h1><p>Votre commande sera confirmée immédiatement et le stock réservé.</p></div></div>
<div class="row g-4"><div class="col-xl-8"><form id="pro-order-form" method="post" action="{{ route('pro.order') }}">@csrf
<section class="bg-white border rounded p-3 p-md-4 mb-3"><h2 class="h5 fw-bold mb-3"><span class="badge text-bg-dark me-2">1</span>Adresse du commerce</h2><div class="row g-3"><div class="col-md-6"><label class="form-label" for="contact_name">Contact</label><input id="contact_name" class="form-control" name="contact_name" value="{{ old('contact_name',$application->manager_name) }}" required></div><div class="col-md-6"><label class="form-label" for="phone">Téléphone</label><input id="phone" class="form-control" name="phone" value="{{ old('phone',$application->phone) }}" required></div><div class="col-md-8"><label class="form-label" for="address">Adresse</label><input id="address" class="form-control" name="address" value="{{ old('address',$application->address) }}" required></div><div class="col-md-4"><label class="form-label" for="city">Ville</label><input id="city" class="form-control" name="city" value="{{ old('city',$application->city) }}" required></div></div></section>
<section class="bg-white border rounded p-3 p-md-4 mb-3"><h2 class="h5 fw-bold mb-3"><span class="badge text-bg-dark me-2">2</span>Mode de paiement</h2><div class="row g-3">
<div class="col-md-6 pro-payment-option"><input id="cash" type="radio" name="payment_method" value="Espèces à la livraison" @checked(old('payment_method','Espèces à la livraison')==='Espèces à la livraison')><label for="cash"><i class="bi bi-cash-stack"></i><span><strong class="d-block">Espèces à la livraison</strong><small class="text-secondary">Payez au livreur après réception et contrôle.</small></span></label></div>
<div class="col-md-6 pro-payment-option"><input id="card" type="radio" name="payment_method" value="Carte bancaire à la livraison" @checked(old('payment_method')==='Carte bancaire à la livraison')><label for="card"><i class="bi bi-credit-card"></i><span><strong class="d-block">Carte bancaire à la livraison</strong><small class="text-secondary">Paiement sécurisé sur le terminal du livreur.</small></span></label></div>
<div class="col-md-6 pro-payment-option"><input id="transfer" type="radio" name="payment_method" value="Virement bancaire" @checked(old('payment_method')==='Virement bancaire')><label for="transfer"><i class="bi bi-bank"></i><span><strong class="d-block">Virement bancaire</strong><small class="text-secondary">Les coordonnées sont envoyées avec la confirmation.</small></span></label></div>
</div></section>
<section class="bg-white border rounded p-3 p-md-4"><label class="form-label" for="notes">Information pour la livraison (facultatif)</label><textarea id="notes" class="form-control" name="notes" rows="3">{{ old('notes') }}</textarea></section>
</form></div><div class="col-xl-4"><div class="pro-summary"><h2 class="h5 fw-bold">Présentoirs commandés</h2>@foreach($displays as $display)<div class="d-flex justify-content-between gap-3 py-2 small"><span>{{ $display->name }} × {{ $display->cart_quantity }}</span><strong class="text-nowrap">{{ number_format($display->wholesale_price_ht*$display->cart_quantity,2,',',' ') }} € HT</strong></div>@endforeach<hr><div class="d-flex justify-content-between"><span>Total HT</span><strong>{{ number_format($subtotalHt,2,',',' ') }} €</strong></div><div class="d-flex justify-content-between py-2"><span>TVA</span><strong>{{ number_format($vatAmount,2,',',' ') }} €</strong></div><div class="d-flex justify-content-between fs-5"><span>Total TTC</span><strong>{{ number_format($totalTtc,2,',',' ') }} €</strong></div><button class="pro-primary-btn btn btn-lg w-100 mt-4" form="pro-order-form"><i class="bi bi-check2-circle me-2"></i>Confirmer la commande</button><p class="small text-secondary text-center mt-2 mb-0">En confirmant, vous réservez le stock du présentoir.</p></div></div></div>
@endsection
